import React,{useState,useEffect} from 'react'
import {Loader,Card,FormField} from '../components'

const Home = () => {
const [Loading, setLoading]=useState(false);
const [allPosts,setAllPosts]=useState(null);

  return (
    <section className='max-w-7x1 mx-auto'>
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">
          The community Showcase
        </h1>
        <p className="mt-2 text-[#666e75] text-[14px] max-w[500px]">
          Browse through a collection of imaginative and visually stunning generated by DALL-E AI
        </p>
      </div>
    </section>
  )
}

export default Home